### PR TITLE
allowing phpunit 8.2 (there are issues with 8.3+ and symfony)

### PR DESCRIPTION
**Pull request by edmondscommerce**

### CODE REVIEW

**Comment by edmondscommerce** [comment]
some conflicts still to work out - WIP

**Comment by edmondscommerce** [comment]
can confirm it now runs

**Comment by edmondscommerce** [comment]
sorry looks like I source formatted (muscle memory)

**Comment by malyMiso** [comment]
Hi @edmondscommerce, thx for PR. 
I really appreciate the changes you've made.
If you want us to accept this PR I would recommend you to create this PR in our [monorepo](https://github.com/shopsys/shopsys), otherwise we are not able to merge it :frowning_face: . Pls. see [Guidelines for Pull Request](https://docs.shopsys.com/en/latest/contributing/guidelines-for-pull-request/)

If you need help with that or you have some questions to ask, let me know, I'll help you

**Pull request closed without merging**
